version: '3'
services:
  web:
    build: .
    ports:
      - "1234:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - reds     
  redis:
    image: "redis:alpine"


    