all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
  children:
    prod:
      hosts:
        app-prod:
          ansible_host: 51.158.121.43
    staging:
      hosts:
        app-staging:
          ansible_host: 51.158.106.69