- name: Setup server
  hosts: all
  tasks:
    - name: Install python3-pip
      apt:
        name: python3-pip
        update_cache: true
    - name: Install docker and docker-compose pip package
      pip:
        name: [ docker, docker-compose ]
    - name: Include geerlingguy.docker role
      include_role:
        name: geerlingguy.docker

    - name: Login to docker registry
      docker_login:
        registry: registry.efrei.yayo.fr
        username: correction
        password: p@ssword