- name: E09
  hosts: all
  tasks:
    - name: install python3-pip with apt
      apt:
        name: python3-pip
        update_cache: true

    - name: install docker and docker-compose pip package
      pip:
        name: [ docker, docker-compose ]

    - name: Install docker
      include_role:
        name: geerlingguy.docker

    - name: Login to registry
      docker_login:
        registry: registry.efrei.yayo.fr
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
