- hosts: all
  tasks:
  
  - name: Install pip
    apt:
      name:  python3-pip
      state: present
      update_cache: yes


  - pip:
      name: 
        - docker
        - docker-compose
      executable: pip3   

  - name: install role 
    include_role:
        name: geerlingguy.docker

  - name: Log into DockerHub
    docker_login:
      registry: registry.efrei.yayo.fr
      username: "{{registry_username}}"
      password: "{{registry_password}}"